spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca_umg
    username: postgres
    password: root20$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

# Opcional: configuración de JWT
security:
  jwt:
#    secret:
    secret: "esta_es_una_clave_larga_de_al_menos_32_bytes_123456"
    expiration-minutes: 60