spring:
  application:
    name: auth-service
  jackson:
    deserialization:
      accept-single-value-as-array: true

  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca_umg
    username: postgres
    password: root20$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

# Opcional: configuración de JWT
security:
  jwt:
    secret: my-password-secret-kvrn1001$-239u54DanielNoriegaAnalisis
    expiration-minutes: 60