server:
  port: 8085

spring:
  cloud:
    gateway:
      # Si quieres remover o añadir filtros globales, hazlo aquí.
      # default-filters:
      #   - RemoveRequestHeader=Cookie    # ❌ NO si vas a usar cookies HttpOnly

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**               # Front llamará /auth/login y /auth/register
          filters:
            # Si quieres impedir que el Authorization del cliente pase al auth-service:
            - RemoveRequestHeader=Authorization

        - id: catalog-service-books
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/libros, /api/v1/libros/**

        - id: catalog-service-authors
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/authors, /api/v1/authors/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://127.0.0.7:5500"   # <--- TU ORIGEN REAL (de la captura)
              - "http://127.0.0.1:5500"
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.security: DEBUG

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "esta_es_una_clave_larga_de_al_menos_32_bytes_123456"
