server:
  port: 8085

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
            
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - RemoveRequestHeader=Authorization
                #- StripPrefix=1

            - id: catalog-service-books
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/libros/**
              filters:
                #- StripPrefix=2
                #- SetPath=/books
                
            - id: catalog-service-authors
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/authors/**
              filters:


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "esta_es_una_clave_larga_de_al_menos_32_bytes_123456"
